# GoReleaser: https://goreleaser.com/intro/
# Release: push a tag (e.g. v0.14.2) and run the workflow or goreleaser release

version: 2

project_name: aurora

builds:
  - id: aurora
    main: ./cmd/aurora
    binary: aurora
    ldflags:
      - -s -w -X github.com/guiferpa/aurora/version.VERSION={{.Version}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

  - id: aurorals
    main: ./cmd/aurorals
    binary: aurorals
    ldflags:
      - -s -w -X github.com/guiferpa/aurora/version.VERSION={{.Version}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    ids:
      - aurora
      - aurorals

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: guiferpa
    name: aurora
  draft: false

# Optional: sign + notarize macOS binaries to avoid Gatekeeper warning (requires Apple Developer account).
# See https://goreleaser.com/customization/binary_sign/ and https://goreleaser.com/customization/notarize/
