export enum ParserNodeTag {
  IDENT = "Ident",
  PARAM = "Parameter",
  NUMERICAL = "Numerical",
  LOGICAL = "Logical",
  NEG_EXPR = "NegativeExpression",
  RELATIVE_EXPR = "RelativeExpression",
  LOGIC_EXPR = "LogicExpression",
  BINARY_OP = "BinaryOperation",
  UNARY_OP = "UnaryOperation",
  IF_STMT = "IfStatement",
  ASSIGN_STMT = "AssignStatement",
  ARITY_STMT = "ArityStatement",
  DECL_FUNC_STMT = "DeclFuncStatement",
  BLOCK_STMT = "BlockStatement",
  CALL_PRINT_STMT = "CallPrintStatement",
  CALL_FUNC_STMT = "CallFuncStatement",
  PROGRAM = "Program",
}
