export enum ParserNodeTag {
  IDENT = "Ident",
  PARAM = "Parameter",
  NUMERICAL = "Numerical",
  LOGICAL = "Logical",
  STRING = "String",
  ARRAY = "Array",
  NEG_EXPR = "NegativeExpression",
  RELATIVE_EXPR = "RelativeExpression",
  LOGIC_EXPR = "LogicExpression",
  BINARY_OP = "BinaryOperation",
  UNARY_OP = "UnaryOperation",
  IF_STMT = "IfStatement",
  ASSIGN_STMT = "AssignStatement",
  ARITY_STMT = "ArityStatement",
  DECL_FUNC_STMT = "DeclFuncStatement",
  BLOCK_STMT = "BlockStatement",
  RETURN_STMT = "ReturnStatement",
  RETURN_VOID_STMT = "ReturnVoidStatement",
  CALL_PRINT_STMT = "CallPrintStatement",
  CALL_ARG_STMT = "CallArgStatement",
  CALL_CONCAT_STMT = "CallConcatStatement",
  CALL_FUNC_STMT = "CallFuncStatement",
  DESC_FUNC_STMT = "DescFuncStatement",
  PROGRAM = "Program",
}
