import { TokenTag } from "./tag";

export const Terminals: [RegExp, TokenTag][] = [
  [new RegExp(/^[0-9_]+/), TokenTag.NUM],
  [new RegExp(/^\"(.*?)"/), TokenTag.STR],
  [new RegExp(/^print/), TokenTag.CALL_PRINT],
  [new RegExp(/^if/), TokenTag.IF],
  [new RegExp(/^not/), TokenTag.NEG],
  [new RegExp(/^true|false/), TokenTag.LOG],
  [new RegExp(/^greater/), TokenTag.REL_GT],
  [new RegExp(/^less/), TokenTag.REL_LT],
  [new RegExp(/^equal/), TokenTag.REL_EQ],
  [new RegExp(/^different/), TokenTag.REL_DIF],
  [new RegExp(/^and/), TokenTag.LOG_AND],
  [new RegExp(/^or/), TokenTag.LOG_OR],
  [new RegExp(/^desc/), TokenTag.DESC_FUNC],
  [new RegExp(/^return void/), TokenTag.RETURN_VOID],
  [new RegExp(/^return/), TokenTag.RETURN],
  [new RegExp(/^var [a-zA-Z_]+(\s?)=/), TokenTag.ASSIGN],
  [new RegExp(/^func [a-zA-Z_]+/), TokenTag.DECL_FN],
  [new RegExp(/^[a-zA-Z_]+/), TokenTag.IDENT],
  [new RegExp(/^\+/), TokenTag.OP_ADD],
  [new RegExp(/^\-/), TokenTag.OP_SUB],
  [new RegExp(/^\*/), TokenTag.OP_MUL],
  [new RegExp(/^\//), TokenTag.OP_DIV],
  [new RegExp(/^\(/), TokenTag.PAREN_O],
  [new RegExp(/^\)/), TokenTag.PAREN_C],
  [new RegExp(/^\{/), TokenTag.BRACK_O],
  [new RegExp(/^\}/), TokenTag.BRACK_C],
  [new RegExp(/^\,/), TokenTag.COMMA],
];
