package ir

func ResolveOpCode(op byte) string {
	switch op {
	case OpMultiply:
		return "OpMultiply"
	case OpAdd:
		return "OpAdd"
	case OpJoin:
		return "OpJoin"
	case OpField:
		return "OpField"
	case OpSubtract:
		return "OpSubtract"
	case OpDivide:
		return "OpDivide"
	case OpExponential:
		return "OpExponential"
	case OpIdent:
		return "OpIdent"
	case OpLoad:
		return "OpLoad"
	case OpBigger:
		return "OpBigger"
	case OpDiff:
		return "OpDiff"
	case OpEquals:
		return "OpEquals"
	case OpSmaller:
		return "OpSmaller"
	case OpBeginScope:
		return "OpBeginScope"
	case OpDefer:
		return "OpDefer"
	case OpSave:
		return "OpSave"
	case OpPreCall:
		return "OpPreCall"
	case OpCall:
		return "OpCall"
	case OpPrintBytes:
		return "OpPrintBytes"
	case OpPrintChars:
		return "OpPrintChars"
	case OpPrintDecimal:
		return "OpPrintDecimal"
	case OpReturn:
		return "OpReturn"
	case OpIf:
		return "OpIf"
	case OpJump:
		return "OpJump"
	case OpOr:
		return "OpOr"
	case OpAnd:
		return "OpAnd"
	case OpPull:
		return "OpPull"
	case OpHead:
		return "OpHead"
	case OpTail:
		return "OpTail"
	case OpPush:
		return "OpPush"
	case OpGetFeed:
		return "OpGetFeed"
	case OpAssert:
		return "OpAssert"
	}
	return "Unknown"
}
