package manifest

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/BurntSushi/toml"
)

const Filename = "aurora.toml"

// DefaultSourceRoot is where module names resolve from when the manifest does not say.
const DefaultSourceRoot = "src"

// DeploysFilename is the hidden file that stores deploy state per profile. Generated by the CLI on deploy; do not edit.
const DeploysFilename = ".aurora.deploys.toml"

const deploysFileHeader = `# This file is generated and managed by the Aurora CLI. Do not edit.
# It stores the last deploy result per profile (contract_address, tx_hash, deployed_at).
# Regenerated on each deploy while keeping state for other profiles.

`

// Manifest is the parsed aurora.toml structure.
type Manifest struct {
	Project  Project                `toml:"project"`
	Profiles map[string]Profile     `toml:"profiles"`
	Deploys  map[string]DeployState `toml:"deploys"`
}

// DeployState holds the last deploy result for a profile. Written by the CLI on each deploy; do not edit by hand.
type DeployState struct {
	ContractAddress string `toml:"contract_address"`
	TxHash          string `toml:"tx_hash"`     // transaction hash of the deploy
	DeployedAt      string `toml:"deployed_at"` // RFC3339
}

// Project holds [project] section.
type Project struct {
	Name    string `toml:"name"`
	Version string `toml:"version"`
	// TapeSize is the width in bytes of every value in this project. Zero means the
	// default (8). A command-line flag overrides it.
	//
	// It belongs to the project rather than to a profile because it is not a path or a
	// setting: it is the dialect the source is written in. At one byte 255 + 1 is 0 and
	// "Gui" does not compile; at eight both answer otherwise. Two profiles with two widths
	// made one file mean two things, and left anything reading the project as a whole —
	// the language server above all — with no width to answer for.
	TapeSize int `toml:"tape_size"`
	// SourceRoot is the directory a module name resolves from: `use a/b/c as x;` reads
	// <source_root>/a/b/c.ar. Empty means the default, "src".
	//
	// It belongs to the project for the same reason tape_size does: it decides what the
	// source means. Two profiles with two roots would make one specifier name two files, and
	// anything reading the project as a whole would have nothing to answer.
	SourceRoot string `toml:"source_root"`
}

// Profile holds a profile section (e.g. [profiles.main]).
type Profile struct {
	Source  string `toml:"source"`
	Binary  string `toml:"binary"`
	RPC     string `toml:"rpc"`
	Privkey string `toml:"privkey"`
}

// FindProjectRoot returns the directory that contains aurora.toml, starting from the current directory and walking up. Returns an error if not found.
func FindProjectRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	return FindProjectRootFrom(dir)
}

// FindProjectRootFrom is the same walk, from a directory given rather than the working one.
// It is what a caller holding a file uses: the project a file belongs to is decided by where
// the file is, not by where the process happens to have been started.
func FindProjectRootFrom(dir string) (string, error) {
	for {
		path := filepath.Join(dir, Filename)
		if _, err := os.Stat(path); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("%s not found in current directory or any parent (run 'aurora init' to create a project manifest)", Filename)
		}
		dir = parent
	}
}

// deploysFile is the structure of .aurora.deploys.toml (sections [deploys.<name>]).
type deploysFile struct {
	Deploys map[string]DeployState `toml:"deploys"`
}

// Load reads and parses the manifest from the given project root directory.
//
// What the manifest says may come from the environment: a value written as ${{ NAME }} is
// read from the project's .env, or from the environment the command runs in when the file
// does not have it. That is what lets a key stay out of a manifest a repository tracks.
//
// It happens after the manifest is parsed, on the values themselves. Doing it on the text
// before would have been shorter and would have read a reference written inside a comment,
// which is not a value — a manifest showing the form in a comment beside a setting would have
// been asked to resolve the example.
//
// Deploy state is read from .aurora.deploys.toml when present; aurora.toml is not modified for
// deploys.
func Load(projectRoot string) (*Manifest, error) {
	path := filepath.Join(projectRoot, Filename)

	var m Manifest
	md, err := toml.DecodeFile(path, &m)
	if err != nil {
		return nil, fmt.Errorf("decode %s: %w", path, err)
	}
	if err := refuseProjectKeysInProfiles(md); err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	if m.Profiles == nil {
		m.Profiles = make(map[string]Profile)
	}
	if err := m.readEnvironment(projectRoot, path); err != nil {
		return nil, err
	}
	m.Deploys = loadDeploysFile(projectRoot)
	if m.Deploys == nil {
		m.Deploys = make(map[string]DeployState)
	}
	return &m, nil
}

// readEnvironment replaces every value that names the environment with what it names.
//
// The fields are written out rather than walked, because a value that may come from outside is
// a decision about that value: a path is a path and a name is a name, and neither is a thing a
// project would keep somewhere else. What is left is what a deploy needs and a manifest should
// not hold.
func (m *Manifest) readEnvironment(projectRoot, path string) error {
	environment, err := LoadEnvironment(projectRoot)
	if err != nil {
		return err
	}

	for name, profile := range m.Profiles {
		where := fmt.Sprintf("%s: profile %s", path, name)
		if profile.RPC, err = environment.Expand(where, profile.RPC); err != nil {
			return err
		}
		if profile.Privkey, err = environment.Expand(where, profile.Privkey); err != nil {
			return err
		}
		m.Profiles[name] = profile
	}
	return nil
}

// loadDeploysFile reads .aurora.deploys.toml and returns the deploys map, or nil if the file is missing.
func loadDeploysFile(projectRoot string) map[string]DeployState {
	path := filepath.Join(projectRoot, DeploysFilename)
	var f deploysFile
	if _, err := toml.DecodeFile(path, &f); err != nil {
		return nil
	}
	if f.Deploys == nil {
		return nil
	}
	return f.Deploys
}

// projectOnlyKeys are the settings that decide what the source means rather than what one
// task does with it. A profile carrying one is refused rather than ignored.
var projectOnlyKeys = []string{"tape_size", "source_root"}

// refuseProjectKeysInProfiles turns a manifest carrying one of those inside a profile into an
// error naming where it sits.
//
// tape_size was a profile field until the width became the project's. Reading it and doing
// nothing would be worse than refusing: a project pinned to one byte would go on compiling at
// eight without a word, and every value in it would change meaning. source_root has never
// been one, and is refused for the same reason before anybody tries.
func refuseProjectKeysInProfiles(md toml.MetaData) error {
	for _, key := range md.Undecoded() {
		if len(key) != 3 || key[0] != "profiles" {
			continue
		}
		for _, name := range projectOnlyKeys {
			if key[2] == name {
				return fmt.Errorf("%s is the project's, not a profile's: move it from [profiles.%s] to [project]", name, key[1])
			}
		}
	}
	return nil
}

// SourceRoot is where module names resolve from, which is "src" unless the project says
// otherwise.
func (m *Manifest) SourceRoot() string {
	if m.Project.SourceRoot == "" {
		return DefaultSourceRoot
	}
	return m.Project.SourceRoot
}

// Profile returns the named profile (e.g. "main") or an error if missing.
func (m *Manifest) Profile(name string) (Profile, error) {
	p, ok := m.Profiles[name]
	if !ok {
		return Profile{}, fmt.Errorf("profile %q not found in manifest", name)
	}
	return p, nil
}

// AbsPath returns path joined with project root (for source, binary).
func AbsPath(projectRoot, path string) string {
	if filepath.IsAbs(path) {
		return path
	}
	return filepath.Join(projectRoot, path)
}

// PersistDeploy writes the deploy result for the given profile to .aurora.deploys.toml. Existing deploy state for other profiles is preserved. Call after a successful deploy.
func PersistDeploy(projectRoot, profileName, address, deployTxHash, deployedAt string) error {
	path := filepath.Join(projectRoot, DeploysFilename)
	state := loadDeploysFile(projectRoot)
	if state == nil {
		state = make(map[string]DeployState)
	}
	state[profileName] = DeployState{
		ContractAddress: address,
		TxHash:          deployTxHash,
		DeployedAt:      deployedAt,
	}
	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("create %s: %w", DeploysFilename, err)
	}
	defer func() {
		if err := f.Close(); err != nil {
			fmt.Fprintf(os.Stderr, "error closing %s: %v\n", DeploysFilename, err)
		}
	}()
	if _, err := f.WriteString(deploysFileHeader); err != nil {
		return fmt.Errorf("write %s header: %w", DeploysFilename, err)
	}
	enc := toml.NewEncoder(f)
	if err := enc.Encode(deploysFile{Deploys: state}); err != nil {
		return fmt.Errorf("encode %s: %w", DeploysFilename, err)
	}
	return nil
}
